from .admin.confirm_link import process_callback
from .admin.create_category import process_callback
from .admin.create_prediction import process_callback
from .admin.remove_category import process_callback
from .admin.remove_prediction import process_callback
from .home import process_callback
from .open_link import process_callback
from .show_categories import process_callback
from .show_predictions import process_callback
from .show_prediction import process_callback
